title: "Rithik's Blog"
description: "Notes, experiments, and learnings from my journey in tech."
author: "Rithik Jha"
email: "rithikkumar53@gmail.com"
theme: minima
show_excerpts: true

minima:
  skin: classic
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/rithikjha" }
