title: "Rithik's Blog"
description: "Notes, experiments, and learnings from my journey in tech."
author: "Rithik Jha"
email: "rithikkumar53@gmail.com"
theme: minima
show_excerpts: true

linkedin_username: rithikjha
