title: "Rithikâ€™s Blog"
description: "Notes, experiments, and learnings from my journey in tech."
url: "https://rithik53.github.io"
baseurl: ""   # keep this empty since this is your main user site

author:
  name: "Rithik"
  email: "your-email@example.com"   # optional

# Use GitHub's default Jekyll theme (simple and clean)
theme: minima

# Markdown + plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: show excerpts on home page
show_excerpts: true

# Where blog posts live
collections:
  posts:
    output: true
